### ISSUE TITLE
crash when file is too large

### ISSUE THREAD

**Issue by felixhao28** [lennym/busboy-body-parser#17]
Hi, thanks for the awesome package! Today I met with an error log appearing on my server when user was uploading a 319mb file:

```
Fatal:
Error: "toString()" failed
    at Buffer.toString (buffer.js:513:11)
    at D:\<project>\node_modules\busboy-body-parser\index.js:42:51
    at ConcatStream.<anonymous> (D:\<project>\node_modules\concat-stream\index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (D:\<project>\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at endWritable (D:\<project>\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at ConcatStream.Writable.end (D:\<project>\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at FileStream.onend (_stream_readable.js:511:10)
    at FileStream.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at FileStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I checked the source code of `index.js` and googled around "nodejs Buffer toString failed error" and found [this](https://github.com/nodejs/node/issues/3175). Since my application does not require the size of the file so I can simply (workaround it)[#16].

I know if the file gets even larger I probably need to find a way to stream data into file instead of memory. But 256mb is not that huge for memory to handle for modern computers.

**Comment by lennym** [comment]
Fixed via #18 and published at v0.3.0
